---
layout: pages-all
---
<div id="page-wrapper" class="page-wrapper">
    <div id="page" class="page">

        <!-- Banner -->
        <div class="jumbotron wrapper">
            <div class="container container-jumbotron banner">
                <div class="col-md-12 banner-content content text-center">
                    <h1 class="text-uppercase">Publications</h1>
                </div>
            </div>
        </div>
        <!-- Banner -->

    </div>
</div>

<p style="text-align: right; margin-top: -40px;"><small>Last updated <i>March 16, 2026&ndash; Pulled automatically from my <a href="https://scholar.google.ca/citations?hl=en&user=WUN5BGgAAAAJ&hl">Google Scholar profile</a>. See <a href="https://thackl.github.io/automatically-update-publications-with-R-scholar">this post</a> for how it works.</small></p>
<h3>2026</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">CAR Warmerdam, HJ Westra, A van der Graaf, MJ Bonder, P Deelen et al. (2026) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4300236376390723806&btnI=1&hl=en">Trans-eQTLs reveal the architecture of human gene regulatory networks</a>, medRxiv, 2026.02. 04.26343575</td></tr>
<tr><td width="100%">Y Zeng, DD Abelman, A Singhawansa, N Cheng, Y Fang, SC Main, E Bell et al. (2026) <a href="https://doi.org/10.1038/s43018-026-01116-3">A pan-cancer compendium of 1,294 plasma cell-free DNA methylomes and fragmentomes enabling multicancer detection</a>, Nat Cancer 7, 384–398 (2026)</td></tr>
<tr><td width="100%">I Nofech-Mozes, A Cook, TW Ouellette, S Hafezi-Bakhtiari, P Awadalla et al. (2026) <a href="https://doi.org/10.64898/2026.01.06.693992">A Pan-Cancer Single-Cell Compendium of Intratumoural Heterogeneity</a>, bioRxiv, 2026.01. 06.693992</td></tr>
<tr><td width="100%">C Díaz-Muñoz, I Bozzarelli, EA Lopera-Maya, L Belbasis, VL Faro et al. (2026) <a href="https://doi.org/10.1136/gutjnl-2025-337059">Genetic dissection of stool frequency implicates vitamin B1 metabolism and other actionable pathways in the modulation of gut motility</a>, Gut </td></tr>
</tbody></table>
<h3>2025</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">K Freimann, A Br&uuml;mmer, R Warmerdam, TS Rupall et al. (2025) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=17764376096785473212&btnI=1&hl=en">Trans-eQTL mapping prioritises USP18 as a negative regulator of interferon response at a lupus risk locus</a>, Nature Communications, 16 (1), 8795</td></tr>
<tr><td width="100%">RJ de Souza, ME Pigeyre, KM Schulze, A Lamri, BK Al-Khazraji et al. (2025) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9017530896487670880&btnI=1&hl=en">Visceral adipose tissue and hepatic fat as determinants of carotid atherosclerosis</a>, Communications medicine, 5 (1), 424</td></tr>
<tr><td width="100%">AA Joy, N Cheng, KA Gelmon, M Mates, C Desbiens, M Clemons et al. (2025) <a href="https://doi.org/10.1158/2767-9764.CRC-25-0346">Continuous versus Standard Palbociclib Treatment and Molecular Profiling of Solid Tissues and Liquid Biopsies in the CCTG MA. 38 Trial in Advanced Breast Cancer</a>, Cancer research communications, 5 (11), 1998-2011</td></tr>
<tr><td width="100%">SM Azab, SS Anand, D Doiron, KM Schulze, JR Brook, M Brauer, D Desai et al. (2025) <a href="https://doi.org/10.1101/2025.10.21.25338504">Association of air pollution with brain health: A cross-sectional analysis in adults living in Canada</a>, medRxiv, 2025.10. 21.25338504</td></tr>
<tr><td width="100%">JRW Kang, YJ Kim, K Skead, D Soave, J Evans, V Bruat, MP Harwood et al. (2025) <a href="https://doi.org/10.1101/2025.10.19.25338239">Geography, Ancestry, Age and Sex Shape Somatic Autosomal Mosaic Chromosomal Alterations in Blood</a>, medRxiv, </td></tr>
<tr><td width="100%">NWF Cheng (2025) <a href="https://utoronto.scholaris.ca/items/67fa8565-f790-47c6-9216-e1b06f36ad86">Early signatures of cancer evolution from cell-free DNA methylation profiling in pre-diagnosis biologics</a>, University of Toronto (Canada), </td></tr>
<tr><td width="100%">JA Barber (2025) <a href="https://utoronto.scholaris.ca/items/1d3e7089-76e5-4545-b97f-8c43fdba4884">Reconstructing the Evolutionary History of Cancer using Single-Cell Sequencing Data</a>, University of Toronto (Canada), </td></tr>
<tr><td width="100%">S Stanton, P Awadalla, L Hughes, SM Vareki (2025) <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11956356/">SITC strategic vision: prevention, premalignant immunity, host and environmental factors</a>, Journal for Immunotherapy of Cancer, 13 (3), e010419</td></tr>
<tr><td width="100%">JJ Connolly, S Sundseth, GM Wood, C Nwaneri, G Ginsburg, P Awadalla et al. (2025) <a href="https://www.nature.com/articles/s43856-025-01026-y">The International Health Cohorts Consortium (IHCC) advances population health research and genomic discovery</a>, Communications Medicine, 5 (1), 366</td></tr>
<tr><td width="100%">N Zhao, A Smargiassi, H Chen, MY Choi, M Fritzler, Z Touma, P Awadalla et al. (2025) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0003496725015225">POS0101 FINE PARTICULATE MATTER AIR POLLUTION AND ANTI-NUCLEAR ANTIBODY POSITIVITY: THE ONTARIO HEALTH STUDY</a>, Annals of the Rheumatic Diseases, 84, 396</td></tr>
<tr><td width="100%">JR Won Kang, V Bruat, K Skead, M Agbessi, J Kim, E Gbeha, MJ Fave et al. (2025) <a href="https://aacrjournals.org/cancerres/article/85/8_Supplement_1/4905/757423">Mosaic chromosomal alterations overlapping hotspot and coldspot sites of somatic structural variation are associated with increased odds of hematological malignancy</a>, Cancer Research, 85 (8_Supplement_1), 4905-4905</td></tr>
<tr><td width="100%">M Darvishian, A Moustaqim‐Barrette, P Awadalla, P Bhatti, P Broet et al. (2025) <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/cam4.70543">Provincial Variation in Adherence to Breast Cancer Screening in Canada: Evidence From the Canadian Partnership for Tomorrow's Health</a>, Cancer Medicine, 14 (6), e70543</td></tr>
<tr><td width="100%">P AWADALLA, F LAMAZE (2025) <a href="https://patents.google.com/patent/US20250043355A1/en">Pan-cancer transcriptional signature</a>, US Patent App., 17/612,695</td></tr>
</tbody></table>
<h3>2024</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">EY Stutheit-Zhao, E Sanz-Garcia, Z Liu, D Wong, K Marsh et al. (2024) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=552353143901217821&btnI=1&hl=en">Early changes in tumor-naive cell-free methylomes and fragmentomes predict outcomes in pembrolizumab-treated solid tumors</a>, Cancer Discovery, 14 (6), 1048-1063</td></tr>
<tr><td width="100%">KY Pan, L Van Tuijl, M Basten, JJM Rijnhart, A De Graeff, J Dekker et al. (2024) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11295592145651181135&btnI=1&hl=en">The mediating role of health behaviors in the association between depression, anxiety and cancer incidence: an individual participant data meta-analysis</a>, Psychological Medicine, 1-14</td></tr>
<tr><td width="100%">S Jovanovska, J Ou, E Youngson, T Choi, C La, E Dvorani, R Saskin et al. (2024) <a href="https://ijpds.org/article/view/2848/5914">Advancements in Pan-Canadian Data Access and Analysis Facilitation: Insights from Collaborative Health Research supported in Alberta, British Columbia, and Ontario</a>, International Journal of Population Data Science, 9 (5)</td></tr>
<tr><td width="100%">J Brooks, A Hayes, R Alvi, M Azimaee, P Bhatti, S Cheema, T Choi et al. (2024) <a href="https://www.researchgate.net/publication/383937833_The_CanPath-HDRN_Canada_Collaboration_Enabling_Multi-jurisdictional_Research_in_Canada">The CanPath-HDRN Canada Collaboration: Enabling Multi-jurisdictional Research in Canada</a>, International Journal of Population Data Science, 9 (5)</td></tr>
<tr><td width="100%">V Ho, I Csizmadi, BA Boucher, M McInerney, C Boileau, N Noisel et al. (2024) <a href="https://bmjopen.bmj.com/content/14/8/e083425">Cohort profile: the CARTaGENE Cohort Nutrition Study (Quebec, Canada)</a>, BMJ open, 14 (8), e083425</td></tr>
<tr><td width="100%">SF O’Brien, M Asamoah-Boaheng, B Grunau, M Krajden, DL Buckeridge et al. (2024) <a href="https://link.springer.com/article/10.17269/s41997-024-00901-w">Canada’s approach to SARS-CoV-2 sero-surveillance: Lessons learned for routine surveillance and future pandemics</a>, Canadian Journal of Public Health, 115 (4), 558-566</td></tr>
<tr><td width="100%">Z Lombard, E Wiener, L Cottino, G Botha, O Nyangiri, H Noyes et al. (2024) <a href="https://pubmed.ncbi.nlm.nih.gov/39041024/">An assessment of the genomic structural variation landscape in Sub-Saharan African populations</a>, Preprint, </td></tr>
<tr><td width="100%">M Basten, KY Pan, LA van Tuijl, A de Graeff, J Dekker, AW Hoogendoorn et al. (2024) <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ijc.34852">Psychosocial factors, health behaviors and risk of cancer incidence: Testing interaction and effect modification in an individual participant data meta‐analysis</a>, International journal of cancer, </td></tr>
<tr><td width="100%">I Nofech-Mozes, V Wang, P Awadalla, S Abelson (2024) <a href="https://aacrjournals.org/cancerres/article/84/6_Supplement/5552/740967">Uncovering clinically significant tumor microenvironment interaction programs across diverse cancers</a>, Cancer Research, 84 (6_Supplement), 5552-5552</td></tr>
<tr><td width="100%">N Cheng, K Skead, T Oullette, S Bratman, D De Carvalho, D Soave et al. (2024) <a href="https://aacrjournals.org/cancerres/article/84/6_Supplement/3454/738235">Cell-free DNA methylation and fragmentomic signatures identify tissue damage and predict cancer risk</a>, Cancer Research, 84 (6_Supplement), 3454-3454</td></tr>
<tr><td width="100%">EY Stutheit-Zhao, E Sanz-Garcia, Z Liu, D Wong, K Marsh et al. (2024) <a href="https://aacrjournals.org/cancerdiscovery/article/doi/10.1158/2159-8290.CD-23-1060/741958/Early-Changes-in-Tumor-Naive-Cell-Free-Methylomes">Early changes in tumor-naive cell-free methylomes and fragmentomes predict outcomes in pembrolizumab-treated solid tumors</a>, Cancer Discovery, </td></tr>
<tr><td width="100%">E Hall, P Awadalla (2024) <a href="https://scholar.google.ca/citations?view_op=view_citation&hl=en&user=WUN5BGgAAAAJ&sortby=pubdate&citation_for_view=WUN5BGgAAAAJ:SAguW2jnL4UC">Age-specific transcriptional risk scores improve patient stratification and outcome predictions for early-onset acute myeloid leukemia</a>, EUROPEAN JOURNAL OF HUMAN GENETICS, 32, 767-767</td></tr>
</tbody></table>
<h3>2023</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">TJ Murphy, H Swail, J Jain, M Anderson, P Awadalla, L Behl, PE Brown et al. (2023) <a href="https://www.cmaj.ca/content/195/31/E1030">The evolution of SARS-CoV-2 seroprevalence in Canada: a time-series study, 2020–2023</a>, CMAJ, 195 (31), E1030-E1037</td></tr>
<tr><td width="100%">LA van Tuijl, M Basten, KY Pan, R Vermeulen, L Portengen, A de Graeff et al. (2023) <a href="https://acsjournals.onlinelibrary.wiley.com/doi/full/10.1002/cncr.34853">Depression, anxiety, and the risk of cancer: An individual participant data meta‐analysis</a>, Cancer, 10.1002/cncr.34853 </td></tr>
<tr><td width="100%">Y Wang, S Namba, E Lopera, S Kerminen, K Tsuo, K L&auml;ll, M Kanai et al. (2023) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9374417867569487935&btnI=1&hl=en">Global Biobank analyses provide lessons for developing polygenic risk scores across diverse cohorts</a>, Cell Genomics, 100241</td></tr>
<tr><td width="100%">W Hill, EL Lim, CE Weeden, C Lee, M Augustine, K Chen, FC Kuan et al. (2023) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7831641566296973806&btnI=1&hl=en">Lung adenocarcinoma promotion by air pollutants</a>, Nature, 616 (7955), 159-167</td></tr>
<tr><td width="100%">VA Kirsh, K Skead, K McDonald, N Kreiger, J Little, K Menard et al. (2023) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12746246072538667343&btnI=1&hl=en">Cohort Profile: The Ontario Health Study (OHS)</a>, International Journal of Epidemiology, 52 (2), e137-e151</td></tr>
<tr><td width="100%">M Darvishian, A Moustaqim-Barrette, P Awadalla, P Bhatti, P Broet et al. (2023) <a href="https://www.frontiersin.org/articles/10.3389/fonc.2023.1113907/full">Provincial variation in colorectal cancer screening adherence in Canada; evidence from the Canadian Partnership for Tomorrow’s Health</a>, Frontiers in Oncology, 13, 1113907</td></tr>
<tr><td width="100%">I Nofech-Mozes, D Soave, P Awadalla, S Abelson (2023) <a href="https://www.nature.com/articles/s41467-023-37353-8">Pan-cancer classification of single cells in the tumour microenvironment</a>, Nature Communications, 14 (1), 1615</td></tr>
<tr><td width="100%">C Calabrese, NR Davidson, D Demircioglu, NA Fonseca, Y He, A Kahles et al. (2023) <a href="https://www.nature.com/articles/s41586-022-05596-y">Author Correction: Genomic basis for RNA alterations in cancer</a>, NATURE </td></tr>
<tr><td width="100%">N Cheng, K Skead, A Singhawansa, T Ouellette, M Elliott, DW Cescon et al. (2023) <a href="https://www.medrxiv.org/content/10.1101/2023.01.30.23285027v1">Pre-diagnosis plasma cell-free DNA methylome profiling up to seven years prior to clinical detection reveals early signatures of breast cancer</a>, medRxiv, 2023.01. 30.23285027</td></tr>
</tbody></table>
<h3>2022</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">G Wong, K Skead, A Mitchell, J McLeod, P Awadalla, E Lechman, J Dick (2022) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0301472X2200563X">3229–MODELING CLONAL HEMATOPOIESIS AND THE PRE-LEUKEMIC STATE WITH CHR13Q DELETION IN HUMAN HEMATOPOIETIC STEM CELLS</a>, Experimental Hematology, 111, S159</td></tr>
<tr><td width="100%">W Zhou, M Kanai, KHH Wu, H Rasheed, K Tsuo, JB Hirbo, Y Wang et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4108825927871003618,13526992530883621795&btnI=1&hl=en">Global Biobank Meta-analysis Initiative: Powering genetic discovery across human disease</a>, Cell Genomics, 2 (10), 100192</td></tr>
<tr><td width="100%">M Kanai, R Elzur, W Zhou, KHH Wu, H Rasheed, K Tsuo, JB Hirbo et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13777671526831018637&btnI=1&hl=en">Meta-analysis fine-mapping is often miscalibrated at single-variant resolution</a>, Cell genomics, 2 (12), 100210</td></tr>
<tr><td width="100%">S Chen, J Petricca, W Ye, J Guan, Y Zeng, N Cheng, L Gong, SY Shen et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4204188247909839202&btnI=1&hl=en">The cell-free DNA methylome captures distinctions between localized and metastatic prostate tumors</a>, Nature Communications, 13 (1), 6467</td></tr>
<tr><td width="100%">CB Joseph, M Mariniello, A Yoshifuji, G Schiano, J Lake, J Marten et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16946895701573533790&btnI=1&hl=en">Meta-GWAS reveals novel genetic variants associated with urinary excretion of uromodulin</a>, Journal of the American Society of Nephrology, 33 (3), 511-529</td></tr>
<tr><td width="100%">SA Norris, CE Draper, A Prioreschi, CM Smuts, LJ Ware, CL Dennis et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3340100161985826860&btnI=1&hl=en">Building knowledge, optimising physical and mental health and setting up healthier life trajectories in South African women (Bukhali): a preconception randomised control trial …</a>, BMJ open, 12 (4), e059914</td></tr>
<tr><td width="100%">SS Anand, MG Friedrich, DS Lee, P Awadalla, JP Després, D Desai et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14631894538484452373&btnI=1&hl=en">Evaluation of Adiposity and Cognitive Function in Adults</a>, JAMA network open, 5 (2), e2146324-e2146324</td></tr>
<tr><td width="100%">N Cheng, K Skead, T Ouellette, S Bratman, D De Carvalho, D Soave et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=725789427030577799&btnI=1&hl=en">Early signatures of breast cancer up to seven years prior to clinical diagnosis in plasma cell-free DNA methylomes</a>, , </td></tr>
<tr><td width="100%">RA Murphy, M Darvishian, J Qi, Y Chen, Q Chu, J Vena, TJB Dummer et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12349496049447654489&btnI=1&hl=en">Lifestyle factors and lung cancer risk among never smokers in the Canadian Partnership for Tomorrow’s Health (CanPath)</a>, Cancer Causes & Control, 33 (6), 913-918</td></tr>
<tr><td width="100%">MP Harwood, I Alves, E H, A M, V Bruat, D Soave, FC Lamaze, MJ Fave et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4298006816833799114&btnI=1&hl=en">Recombination affects allele-specific expression of deleterious variants in human populations</a>, Science Advances, 8 (19), 1-12</td></tr>
<tr><td width="100%">T Ouellette, P Awadalla (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13710271577590335677&btnI=1&hl=en">Inferring ongoing cancer evolution from single tumour biopsies using synthetic supervised learning</a>, PLOS Computational Biology, 18 (4), e1010007</td></tr>
<tr><td width="100%">JM Luu, C Gebhard, C Ramasundarahettige, D Desai, K Schulze et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13589042205732362077&btnI=1&hl=en">Normal sex and age-specific parameters in a multi-ethnic population: a cardiovascular magnetic resonance study of the Canadian Alliance for Healthy Hearts and Minds cohort</a>, Journal of Cardiovascular Magnetic Resonance, 24 (1), 1-13</td></tr>
<tr><td width="100%">R Urquhart, P Awadalla, P Bhatti, T Dummer, S Gravel, J Vena, R Alvi et al. (2022) <a href="https://ijpds.org/article/view/1950">Harnessing the power of data linkage to enrich the cancer research ecosystem in Canada.</a>, International Journal of Population Data Science, 7 (3)</td></tr>
<tr><td width="100%">VA Kirsh, K Skead, K McDonald, N Kreiger, J Little, K Menard et al. (2022) <a href="https://academic.oup.com/ije/advance-article-abstract/doi/10.1093/ije/dyac156/6665820?redirectedFrom=fulltext">Cohort Profile: The Ontario Health Study (OHS)</a>, International Journal of Epidemiology, </td></tr>
<tr><td width="100%">N Cheng, D Soave, K Skead, T Ouellette, S Bratman, D De Carvalho et al. (2022) <a href="https://aacrjournals.org/cancerres/article/82/12_Supplement/3385/700154">Pre-diagnosis plasma cell-free DNA methylation profiling reveals signatures of cancers up to7 years prior to clinical detection</a>, Cancer Research, 82 (12_Supplement), 3385-3385</td></tr>
<tr><td width="100%">I Nofech-Mozes, P Awadalla, S Abelson (2022) <a href="https://aacrjournals.org/cancerres/article/82/12_Supplement/1221/703618">Comprehensive cell-type classification of tumor and normal cells from single cell RNA sequencing in pan cancer settings</a>, Cancer Research, 82 (12_Supplement), 1221-1221</td></tr>
<tr><td width="100%">K Skead, D Soave, MJ Fave, V Bruat, Q Morris, P Awadalla (2022) <a href="https://aacrjournals.org/cancerres/article/82/12_Supplement/2228/700201">A multi-omic perspective of how selection shapes blood cancer risk phenotypes in aging populations</a>, Cancer Research, 82 (12_Supplement), 2228-2228</td></tr>
<tr><td width="100%">TW Ouellette, P Awadalla (2022) <a href="https://aacrjournals.org/cancerres/article/82/12_Supplement/6090/700278">Disentangling subclonal dynamics in growing tumors using stochastic simulations and Bayesian neural networks</a>, Cancer Research, 82 (12_Supplement), 6090-6090</td></tr>
<tr><td width="100%">I Nofech-Mozes, D Soave, P Awadalla, S Abelson (2022) <a href="https://www.biorxiv.org/content/10.1101/2022.06.14.496107v1.full">Pan-cancer classification of single cells in the tumour microenvironment</a>, bioRxiv, </td></tr>
</tbody></table>
<h3>2021</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">QTL consortium (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=643297697688849439&btnI=1&hl=en">Large-scale cis-and trans-eQTL analyses identify thousands of genetic loci and polygenic scores that regulate blood gene expression</a>, Nature Genetics, 1-11</td></tr>
<tr><td width="100%">K Bolton, Y Koh, M Foote, H Im, J Lee, CH Sun, A Safanov, R Ptashkin et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14953672075687069527&btnI=1&hl=en">Clonal hematopoiesis is associated with risk of severe Covid-19</a>, Nature Communications, 12 (5975), 1-8</td></tr>
<tr><td width="100%">Y Wang, S Namba, EA Lopera-Maya, S Kerminen, K Tsuo, K Lall, M Kanai et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14026823586699889026&btnI=1&hl=en">Global biobank analyses provide lessons for computing polygenic risk scores across diverse cohorts</a>, medRxiv, </td></tr>
<tr><td width="100%">R Durrani, MG Friedrich, KM Schulze, P Awadalla, K Balasubramanian et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6551605787298600967&btnI=1&hl=en">Effect of Cognitive Reserve on the Association of Vascular Brain Injury With Cognition: Analysis of the PURE and CAHHM Studies</a>, Neurology, 97 (17), e1707-e1716</td></tr>
<tr><td width="100%">J Tremblay, M Haloui, R Attaoua, R Tahir, C Hishmih, F Harvey et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5473485908335879987&btnI=1&hl=en">Polygenic risk scores predict diabetes complications and their response to intensive blood pressure and glucose control</a>, Diabetologia, 64 (9), 2012-2025</td></tr>
<tr><td width="100%">K Skead, AA Houle, S Abelson, M Agbessi, V Bruat, B Lin, D Soave et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7425984139198320187&btnI=1&hl=en">Interacting evolutionary pressures drive mutation dynamics and health outcomes in aging blood</a>, Nature Communications, 12 (1), 1-11</td></tr>
<tr><td width="100%">LA van Tuijl, AC Voogd, A de Graeff, AW Hoogendoorn, AV Ranchor et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7897327634658290886&btnI=1&hl=en">Psychosocial factors and cancer incidence (PSY‐CA): Protocol for individual participant data meta‐analyses</a>, Brain and behavior, 11 (10), e2340</td></tr>
<tr><td width="100%">HC Gerstein, EE Smith, C Ramasundarahettige, D Desai, P Awadalla et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=17205735332103341076&btnI=1&hl=en">Diabetes, brain infarcts, cognition, and small vessels in the Canadian alliance for healthy hearts and minds study</a>, The Journal of Clinical Endocrinology & Metabolism, 106 (2), e891-e898</td></tr>
<tr><td width="100%">TW Ouellette, J Shaw, P Awadalla (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11460186975434590755&btnI=1&hl=en">Using image-based haplotype alignments to map global adaptation of SARS-CoV-2</a>, bioRxiv, </td></tr>
<tr><td width="100%">T Ouellette, P Awadalla (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Inferring ongoing cancer evolution from single tumour biopsies using synthetic supervised learning</a>, BioRxiv, </td></tr>
<tr><td width="100%">E Sweeney, P Awadalla, P Bhatti, P Broet, T Dummer, J McLaughlin et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">The Utility of Occupational Health Data in the Canadian Partnership for Tomorrow’s Health (CanPath)</a>, Occupational and Environmental Medicine, 78 (Suppl 1), A61-A62</td></tr>
<tr><td width="100%">D Soave, JF Lawless, P Awadalla (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Score tests for scale effects, with application to genomic analysis</a>, Statistics in Medicine, 40 (16), 3808-3822</td></tr>
<tr><td width="100%">N Cheng, K Skead, D Soave, J Meng, E Gbeha, I Lungu, B Lam et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Leveraging cell-free methylome markers for early cancer detection</a>, Cancer Research, 81 (13 Supplement), 2602-2602</td></tr>
<tr><td width="100%">C Parra-Herran, F Lamaze, S Nofech-Mozes, T Ouellette, J Uzunovic et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">CNV Signature Model is Highly Accurate in the Distinction Between Primary Ovarian Mucinous Carcinoma and Gastrointestinal Adenocarcinoma</a>, LABORATORY INVESTIGATION, 101 (SUPPL 1), 727-728</td></tr>
<tr><td width="100%">H Trochet, J Pelletier, JC Grenier, MJ Favé, P Awadalla, J Hussin (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">The relationship between reproductive lifespan and coronary artery disease</a>, Canadian Journal of Cardiology, 37 (2), e21</td></tr>
<tr><td width="100%">A Choudhury, S Aron, LR Botigue, D Sengupta, G Botha, T Bensellak et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">High-depth African genomes inform human migration and health (vol 586, pg 741, 2020)</a>, Nature, 592 (7856), E26-E26</td></tr>
</tbody></table>
<h3>2020</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">PCAWG Consortium (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9874508862688546280,16882476473286707718,17361616063170219816,14017499499035774109&btnI=1&hl=en">Pan-cancer analysis of whole genomes.</a>, Nature, 578 (7793), 82-93</td></tr>
<tr><td width="100%">C Calabrese, NR Davidson, D Demircioğlu, NA Fonseca, Y He, A Kahles et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=43639809640911032&btnI=1&hl=en">Genomic basis for RNA alterations in cancer</a>, Nature, 578 (7793), 129-136</td></tr>
<tr><td width="100%">H3Africa (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=17245206875860945494&btnI=1&hl=en">High-depth African Genomes Inform Human Migration and Health</a>, Nature, 586, 741-748</td></tr>
<tr><td width="100%">PCAWG (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9387543439572440561&btnI=1&hl=en">High-coverage whole-genome analysis of 1220 cancers reveals hundreds of genes deregulated by rearrangement-mediated cis-regulatory alterations.</a>, Nature Communications, 11 (5), 736</td></tr>
<tr><td width="100%">AR Hammerschlag, EM Byrne, M Agbessi, H Ahsan, I Alves, A Andiappan et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15989789422437630562&btnI=1&hl=en">Refining attention-deficit/hyperactivity disorder and autism spectrum disorder genetic loci by integrating summary data from genome-wide association, gene expression, and DNA …</a>, Biological Psychiatry, 88 (6), 470-479</td></tr>
<tr><td width="100%">SS Anand, JV Tu, D Desai, P Awadalla, P Robson, S Jacquemont et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2170036013704963037&btnI=1&hl=en">Cardiovascular risk scoring and magnetic resonance imaging detected subclinical cerebrovascular disease</a>, European Heart Journal-Cardiovascular Imaging, 21 (6), 692-700</td></tr>
<tr><td width="100%">N Zhao, A Smargiassi, M Hatzopoulou, I Colmegna, M Hudson, MJ Fritzler et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4656337349334470339&btnI=1&hl=en">Long-term exposure to a mixture of industrial SO2, NO2, and PM2. 5 and anti-citrullinated protein antibody positivity</a>, Environmental Health, 19 (1), 1-8</td></tr>
<tr><td width="100%">SS Anand, MG Friedrich, D Desai, KM Schulze, P Awadalla, D Busseuil et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3184616063786572184&btnI=1&hl=en">Reduced Cognitive Assessment Scores Among Individuals With Magnetic Resonance Imaging–Detected Vascular Brain Injury</a>, Stroke, 51 (4), 1158-1165</td></tr>
<tr><td width="100%">S Abelson, AGX Zeng, I Nofech-Mozes, TT Wang, SWK Ng, MD Minden et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4663655485454023895&btnI=1&hl=en">Integration of intra-sample contextual error modeling for improved detection of somatic mutations from deep sequencing</a>, Science advances, 6 (50), eabe3722</td></tr>
<tr><td width="100%">KL Bolton, M Foote, J Jee, A Safonov, R Ptashkin, S Devlin, E Gedvilaite et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4852925121180237948&btnI=1&hl=en">Clonal hematopoiesis and COVID-19 severity in cancer patients</a>, Blood, 136, 37-38</td></tr>
<tr><td width="100%">C Parra-Herran, S Nofech-Mozes, J Uzunovic, F Lamaze, I Lungu, C Ptak et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6880223564535451823&btnI=1&hl=en">Comprehensive Genomic Characterization of Primary Ovarian Mucinous Carcinoma</a>, LABORATORY INVESTIGATION, 100 (SUPPL 1), 1116-1117</td></tr>
<tr><td width="100%">L Stein, C Yung, P Awadalla, C Williams, L Radvanyi, J Adams et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">A Standards-Based Digital Infrastructure for Secure Sharing of Human Biomedical Research Data</a>, , </td></tr>
<tr><td width="100%">K Skead, AA Houle, S Abelson, MJ Fave, B Lin, D Soave, S Wright et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Opposing Evolutionary Pressures Drive Clonal Evolution and Health Outcomes in the Aging Blood System</a>, Blood, 136, 37</td></tr>
<tr><td width="100%">RE Hall, N Tusevljak, CF Wu, Q Ibrahim, K Schulze, AM Khan, D Desai et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">The Canadian Alliance for Healthy Hearts and Minds: How Well Does It Reflect the Canadian Population?</a>, CJC open, 2 (6), 599-609</td></tr>
<tr><td width="100%">WU Meyerson, LJ Dursi, LB Wang, G Dong, WW Liang, A Weerasinghe et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Retrospective evaluation of whole exome and genome mutation calls in 746 cancer samples</a>, Nature Publishing Group UK, </td></tr>
<tr><td width="100%">SD Prokopec, RX Sun, F Yousif, N Schmitz, F Al-Shahrour, G Atwal et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Sex differences in oncogenic mutational processes</a>, Nature Publishing Group UK, </td></tr>
<tr><td width="100%">K Skead, AA Houle, S Abelson, M Agbessi, V Bruat, B Lin, D Soave et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Interacting evolutionary pressures drive mutation dynamics and health outcomes in aging blood</a>, BioRxiv, </td></tr>
<tr><td width="100%">C Calabrese, NR Davidson, D Demircioglu, NA Fonseca, Y He, A Kahles et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Intraplate volcanism originating from upwelling hydrous mantle transition zone</a>, , </td></tr>
</tbody></table>
<h3>2019</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">MR Team, QTL Consortium, IC Consortium (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4895631616621620461,8847148419995654677&btnI=1&hl=en">Genome-wide association analyses of risk tolerance and risky behaviors in over 1 million individuals identify hundreds of loci and shared genetic influences</a>, Nature Genetics, </td></tr>
<tr><td width="100%"> (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7396363427662591592&btnI=1&hl=en">Genomics of 1 million parent lifespans implicates novel pathways and common diseases and distinguishes survival chances</a>, elife, e, e39856</td></tr>
<tr><td width="100%">E Porcu, S R&uuml;eger, K Lepik, FA Santoni, A Reymond, Z Kutalik (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4828053715630643997&btnI=1&hl=en">Mendelian randomization integrating GWAS and eQTL data reveals genetic determinants of complex and clinical traits</a>, Nature communications, 10 (1), 1-12</td></tr>
<tr><td width="100%">E Lowy-Gallego, S Fairley, X Zheng-Bradley, M Ruffier, L Clarke, P Flicek et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10212301061188785283&btnI=1&hl=en">Variant calling on the GRCh38 assembly with the data from phase three of the 1000 Genomes Project</a>, Wellcome Open Research, 4</td></tr>
<tr><td width="100%">X Shao, M Hudson, I Colmegna, CMT Greenwood, MJ Fritzler, P Awadalla et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4424873042688130323&btnI=1&hl=en">Rheumatoid arthritis-relevant DNA methylation changes identified in ACPA-positive asymptomatic individuals using methylome capture sequencing</a>, Clinical epigenetics, 11 (1), 1-11</td></tr>
<tr><td width="100%">A Krajcoviechova, FC Marois-Blanchet, S Troyanov, F Harvey, P Dumas et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1670238222307145335&btnI=1&hl=en">Uromodulin in a pathway between decreased renal urate excretion and albuminuria</a>, American journal of hypertension, 32 (4), 384-392</td></tr>
<tr><td width="100%">N Zhao, A Smargiassi, M Hatzopoulou, I Colmegna, M Hudson, M Fritzler et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8429424616704864424&btnI=1&hl=en">Multiple industrial air pollutants and anti-citrullinated protein antibody positivity</a>, ARTHRITIS & RHEUMATOLOGY, 71</td></tr>
<tr><td width="100%">J Tremblay, M Haloui, F Harvey, R Tahir, FC Marois-Blanchet, C Long et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4831940747993576755&btnI=1&hl=en">Polygenic risk scores predict diabetic complications and their response to therapy</a>, MedRxiv, 19010785</td></tr>
<tr><td width="100%">P Awadalla (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">133-The Canadian Partnership for Tomorrow Project: Canada’s Longitudinal Population Laboratory</a>, Canadian Journal of Diabetes, 43 (7), S45</td></tr>
</tbody></table>
<h3>2018</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">S Abelson, G Collord, SWK Ng, O Weissbrod, N Mendelson Cohen et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11109893273549688922&btnI=1&hl=en">Prediction of acute myeloid leukaemia risk in healthy individuals</a>, Nature, 559 (7714), 400-404</td></tr>
<tr><td width="100%">Consortium, eQTL (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2406570209186643212&btnI=1&hl=en">Genome-wide association analyses identify 143 risk variants and putative regulatory mechanisms for type 2 diabetes.</a>, Nature Communications, 9 (1), 2941</td></tr>
<tr><td width="100%">U Võsa, A Claringbould, HJ Westra, MJ Bonder, P Deelen, B Zeng et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6578196114977590979&btnI=1&hl=en">Unraveling the polygenic architecture of complex traits using blood eQTL metaanalysis</a>, BioRxiv, 447367</td></tr>
<tr><td width="100%">Consortium, eQTL (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16292895834231011824&btnI=1&hl=en">Identifying gene targets for brain-related traits using transcriptomic and methylomic data from blood.</a>, Nature Communications, 9 (1), 2282</td></tr>
<tr><td width="100%">MJ Favé, FC Lamaze, D Soave, A Hodgkinson, H Gauvin, V Bruat et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3206812341606223445&btnI=1&hl=en">Gene-by-environment interactions in urban populations modulate risk phenotypes</a>, Nature communications, 9 (1), 1-12</td></tr>
<tr><td width="100%">TJB Dummer, P Awadalla, C Boileau, C Craig, I Fortier, V Goel, JMT Hicks et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5986075399974382646&btnI=1&hl=en">The Canadian Partnership for Tomorrow Project: a pan-Canadian platform for research on chronic disease prevention</a>, Cmaj, 190 (23), E710-E717</td></tr>
<tr><td width="100%">S Peischl, I Dupanloup, A Foucal, M Jomphe, V Bruat, JC Grenier, A Gouy et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3983721762276964806&btnI=1&hl=en">Relaxed selection during a recent human expansion</a>, Genetics, 208 (2), 763-777</td></tr>
<tr><td width="100%">AA Houle, H Gibling, FC Lamaze, HA Edgington, D Soave, MJ Fave et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16384185012039504669&btnI=1&hl=en">Aberrant PRDM9 expression impacts the pan-cancer genomic landscape</a>, Genome research, 28 (11), 1611-1620</td></tr>
<tr><td width="100%">TC PCAWG (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11919198225723971130,11362451867629372087,17844646006132515584,9653583119139095848&btnI=1&hl=en">Genomic basis for RNA alterations revealed by whole-genome analyses of 27 cancer types</a>, bioRxiv, 183889</td></tr>
<tr><td width="100%">A Krajcoviechova, F Marois-Blanchet, S Troyanov, F Harvey, P Dumas et al. (2018) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">URINARY UROMODULIN IN A PATHWAY BETWEEN DECREASED URINARY URIC ACID EXCRETION AND ALBUMINURIA</a>, Journal of Hypertension, 36, e119</td></tr>
</tbody></table>
<h3>2017</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">EJ Gardner, VK Lam, DN Harris, NT Chuang, EC Scott, WS Pittard et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9605936454822412466&btnI=1&hl=en">The Mobile Element Locator Tool (MELT): population-scale mobile element discovery and biology</a>, Genome research, 27 (11), 1916-1929</td></tr>
<tr><td width="100%">DA Knowles, JR Davis, H Edgington, A Raj, MJ Favé, X Zhu, JB Potash et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8413021581368423255&btnI=1&hl=en">Allele-specific expression reveals interactions between genetic variation and environment</a>, Nature methods, 14 (7), 699-702</td></tr>
<tr><td width="100%">X Zheng-Bradley, I Streeter, S Fairley, D Richardson, L Clarke, P Flicek et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=430588140821348545&btnI=1&hl=en">Alignment of 1000 Genomes Project reads to reference assembly GRCh38</a>, Gigascience, 6 (7), gix038</td></tr>
<tr><td width="100%">I Alves, AA Houle, JG Hussin, P Awadalla (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7879128504398120261&btnI=1&hl=en">The impact of recombination on human mutation load and disease</a>, Philosophical Transactions of the Royal Society B: Biological Sciences, 372 …</td></tr>
<tr><td width="100%">FC Lamaze, A Chateigner, HA Edgington, MJ Fave, AA Houle et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3158644101806858499&btnI=1&hl=en">Motif disruption domains lead to cancer gene expression rewiring</a>, bioRxiv, 126359</td></tr>
<tr><td width="100%">S Abelson, SWK Ng, O Wiessbrod, P Zuzarte, L Heisler et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7358051398306969269&btnI=1&hl=en">Progression to AML is predictable and distinct from age related clonal hematopoiesis</a>, Blood, 130, 471</td></tr>
<tr><td width="100%">S Amin, P Awadalla, A Biankin, P Boutros, A Brazma, AN Brooks et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Abstract SY10-02: Pan-cancer study of recurrent and heterogeneous RNA aberrations and association with whole-genome variants</a>, Cancer Research, 77 (13 Supplement), SY10-02-SY10-02</td></tr>
<tr><td width="100%">MJ Favé, FC Lamaze, A Hodgkinson, H Gauvin, V Bruat, JC Grenier et al. (2017) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Genomic and Environmental Contributions to Chronic Diseases in Urban Populations</a>, bioRxiv, 099770</td></tr>
</tbody></table>
<h3>2016</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">GD Poznik, Y Xue, FL Mendez, GP Consortium, CD Bustamante et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12017336074654870496&btnI=1&hl=en">Punctuated bursts in human male demography inferred from 1,244 worldwide Y-chromosome sequences</a>, Nature Genetics, 48 (6), 593-599</td></tr>
<tr><td width="100%">KR Kukurba, P Parsana, B Balliu, KS Smith, Z Zappala, DA Knowles et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14226056292621647639&btnI=1&hl=en">Impact of the X chromosome and sex on regulatory variation</a>, Genome research, 26 (6), 768-777</td></tr>
<tr><td width="100%">N Schmitz, SS Deschênes, RJ Burns, KJ Smith, A Lesage, I Strychar et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15788003729257453455&btnI=1&hl=en">Depression and risk of type 2 diabetes: the potential role of metabolic factors</a>, Molecular Psychiatry, </td></tr>
<tr><td width="100%">C Preuss, M Capredon, F W&uuml;nnemann, P Chetaille, A Prince, B Godard et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13990586859123229073&btnI=1&hl=en">Family based whole exome sequencing reveals the multifaceted role of notch signaling in congenital heart disease</a>, PLoS genetics, 12 (10), e1006335</td></tr>
<tr><td width="100%">I Bourdeau, S Oble, F Magne, I Lévesque, KY Cáceres-Gorriti, S Nolet et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1832741592717261519&btnI=1&hl=en">ARMC5 mutations in a large French-Canadian family with cortisol-secreting b-adrenergic/vasopressin responsive bilateral macronodular adrenal hyperplasia</a>, Eur J Endocrinol, 174 (1), 85-96</td></tr>
<tr><td width="100%">ND Merner, A Mercado, AR Khanna, A Hodgkinson, V Bruat, P Awadalla et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6689226687409835840&btnI=1&hl=en">Gain-of-function missense variant in SLC12A2, encoding the bumetanide-sensitive NKCC1 cotransporter, identified in human schizophrenia</a>, Journal of psychiatric research, 77, 22-26</td></tr>
<tr><td width="100%">S Troyanov, C Delmas-Frenette, G Bollée, S Youhanna, V Bruat et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16216537853369720121&btnI=1&hl=en">Clinical, genetic, and urinary factors associated with uromodulin excretion</a>, Clinical Journal of the American Society of Nephrology, 11 (1), 62-69</td></tr>
<tr><td width="100%">SS Anand, JV Tu, P Awadalla, S Black, C Boileau, D Busseuil, D Desai et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12575375979547119597&btnI=1&hl=en">Rationale, design, and methods for Canadian alliance for healthy hearts and minds cohort study (CAHHM)–a Pan Canadian cohort study</a>, BMC public health, 16 (1), 1-15</td></tr>
<tr><td width="100%">F W&uuml;nnemann, V Kokta, S Leclerc, M Thibeault, C McCuaig, A Hatami et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15501239681983184089&btnI=1&hl=en">Aortic dilatation associated with a de novo mutation in the SOX18 gene: expanding the clinical spectrum of hypotrichosis-lymphedema-telangiectasia syndrome</a>, Canadian Journal of Cardiology, 32 (1), 135. e1-135. e7</td></tr>
<tr><td width="100%">A Hodgkinson, JC Grenier, E Gbeha, P Awadalla (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9268386915169505134&btnI=1&hl=en">A haplotype-based normalization technique for the analysis and detection of allele specific expression</a>, BMC bioinformatics, 17 (1), 1-10</td></tr>
<tr><td width="100%">S Gomez, A Diawara, E Gbeha, P Awadalla, A Sanni, Y Idaghdour et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6828670023806781048&btnI=1&hl=en">Comparative Analysis of Iron Homeostasis in Sub-Saharan African Children with Sickle Cell Disease and Their Unaffected Siblings</a>, Frontiers Pediatrics, </td></tr>
<tr><td width="100%">V Kumar, HJ Westra, J Karjalainen, DV Zhernakova, T Esko, B Hrdlickova et al. (2016) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Genome-wide association study in asian populations identifies variants in ETS1 and WDFY4 associated with systemic lupus erythematosus</a>, Nature, </td></tr>
</tbody></table>
<h3>2015</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">1000 Genomes Project Consortium (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4920627857991727214,9638401039211227985,5692838472292138295&btnI=1&hl=en">A global reference for human genetic variation.</a>, Nature, 526 (7571), 68-74</td></tr>
<tr><td width="100%">PH Sudmant, T Rausch, EJ Gardner, RE Handsaker, A Abyzov et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5695407377079785877&btnI=1&hl=en">An integrated map of structural variation in 2,504 human genomes.</a>, Nature, 526 (7571), 75-81</td></tr>
<tr><td width="100%">Genomes Project Consortium (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1008270268668369708&btnI=1&hl=en">Auton A, Brooks LD, Durbin RM, Garrison EP, Kang HM, Korbel JO, Marchini JL, McCarthy S, McVean GA, Abecasis GR. A global reference for human genetic variation</a>, Nature, 526 (7571), 68-74</td></tr>
<tr><td width="100%">JG Hussin, A Hodgkinson, Y Idaghdour, JC Grenier, JP Goulet, E Gbeha et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9362500027337734317&btnI=1&hl=en">Recombination affects accumulation of damaging and disease-associated mutations in human populations</a>, Nature genetics, 47 (4), 400-404</td></tr>
<tr><td width="100%">1000 Genomes Project Consortium (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5330920706395125264&btnI=1&hl=en">Auton A, Brooks LD, Durbin RM, Garrison EP, Kang HM, Korbel JO, Marchini JL, McCarthy S, McVean GA, Abecasis GR. A global reference for human genetic variation</a>, Nature, 526 (7571), 68-74</td></tr>
<tr><td width="100%">Leblond CS, Gan-Or Z, Spiegelman D, Laurent SB, Szuto A, Hodgkinson A ... (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4461717804892510195&btnI=1&hl=en">Replication study of MATR3 in familial and sporadic amyotrophic lateral sclerosis</a>, Neurobiology of Aging, </td></tr>
<tr><td width="100%">ELB Rana, MR Tahir, J Tremblay, M Joffres, O Šeda, L Šedová et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14817043995183161877&btnI=1&hl=en">Association of age-dependent height and bone mineral density decline with increased arterial stiffness and rate of fractures in hypertensive individuals</a>, Journal of Hypertension, 33 (4), 727-735</td></tr>
<tr><td width="100%">S Bernatsky, X Shao, MM Simon, MJ Fritzler, P Awadalla, M Hudson et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">DNA Methylation and Its Relation to Immunological Phenotypes in Peripheral Blood: A Study of Anti-CCP Antibody Positivity from a Population-Based Pool</a>, ARTHRITIS & RHEUMATOLOGY, 67</td></tr>
<tr><td width="100%">Y Fu, Z Liu, S Lou, V Colonna, J Bedford, X Mu, KY Yip, HM Kang et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">A computational framework for prioritizing noncoding regulatory variants in cancer</a>, Cancer Research, 75 (15 Supplement), 4854-4854</td></tr>
<tr><td width="100%">S Bernatsky, M Fritzler, M Hudson, I Colmegna, P Fortin, A Brand et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Industrial Pollution Emissions are associated with Anti-CCP Antibodies</a>, JOURNAL OF RHEUMATOLOGY, 42 (7), 1316-1317</td></tr>
<tr><td width="100%">JT Simpson, M Cerezo, C Churchhouse, DM Altshuler, Y Lu, D Kim et al. (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">A global reference for human genetic variation</a>, Springer, </td></tr>
</tbody></table>
<h3>2014</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">O Delaneau, J Marchini (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5910031341477968704&btnI=1&hl=en">Integrating sequence and array data to create an improved 1000 Genomes Project haplotype reference panel</a>, Nature communications, 5 (1), 1-9</td></tr>
<tr><td width="100%">T Willems, M Gymrek, G Highnam, GP Consortium, D Mittelman, Y Erlich (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6414372168771803105&btnI=1&hl=en">The landscape of human STR variation</a>, Genome Research, 24 (11), 1894-904</td></tr>
<tr><td width="100%">K Kahle, N Merner, P Friedel, L Silayeva, B Liang, A Khanna, Y Shang et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15791485108864967529&btnI=1&hl=en">Genetically encoded impairment of neuronal KCC2 cotransporter function in human idiopathic generalized epilepsy.</a>, EMBO Reports, 15 (7), 766-74</td></tr>
<tr><td width="100%">A Hodgkinson, Y Idaghdour, E Gbeha, JC Grenier, E Hip-Ki, V Bruat et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3496235138422896059&btnI=1&hl=en">High-resolution genomic analysis of human mitochondrial RNA sequence variation</a>, Science, 344 (6182), 413-415</td></tr>
<tr><td width="100%">V Colonna, TGP Consortium (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5141785107488587625&btnI=1&hl=en">Human genomic regions with exceptionally high levels of population differentiation identified from 911 whole-genome sequences.</a>, Genome Biology, 15 (6), R88</td></tr>
<tr><td width="100%">JC Verhave, S Troyanov, F Mongeau, L Fradette, J Bouchard, P Awadalla et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16594019934220011639&btnI=1&hl=en">Prevalence, awareness, and management of CKD and cardiovascular risk factors in publicly funded health care</a>, Clinical journal of the American Society of Nephrology, 9 (4), 713-719</td></tr>
<tr><td width="100%">J Quinlan, Y Idaghdour, JP Goulet, E Gbeha, T de Malliard, V Bruat et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6554633805947190050&btnI=1&hl=en">Genomic architecture of sickle cell disease in West African children</a>, Frontiers in genetics, 5, 26</td></tr>
<tr><td width="100%">C Delmas-Frenette, S Troyanov, P Awadalla, O Devuyst, F Madore (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">ASSOCIATIONS BETWEEN A UMOD GENE VARIANT, UROMODULIN EXCRETION AND RENAL FUNCTION IN A LARGE CANADIAN SURVEY: THE CARTAGENE STUDY</a>, NEPHROLOGY DIALYSIS TRANSPLANTATION, 29, 149-149</td></tr>
<tr><td width="100%">I Kurnatowska, P Grzelak, A Masajtis-Zagajewska, M Kaczmarska et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">CKD pathophysiology and clinical studies</a>, Nephrology Dialysis Transplanation, 29 (suppl_3), iii148-iii167</td></tr>
<tr><td width="100%">V Colonna, Q Ayub, Y Chen, L Pagani, P Luisi, M Pybus, E Garrison et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Human genomic regions with exceptionally high or low levels of population differentiation identified from 911 whole-genome sequences</a>, bioRxiv, 005462</td></tr>
<tr><td width="100%">JG Hussin, A Hodgkinson, Y Idaghdour, JC Grenier, JP Goulet, E Gbeha et al. (2014) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Recombination impacts damaging and disease mutation accumulation in human populations</a>, bioRxiv, 006064</td></tr>
</tbody></table>
<h3>2013</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">E Khurana, Y Fu, V Colonna, XJ Mu, HM Kang, T Lappalainen, A Sboner et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16254837286944213160&btnI=1&hl=en">Integrative annotation of variants from 1092 humans: application to cancer genomics</a>, Science, 342 (6154), 1235587</td></tr>
<tr><td width="100%">SR Grossman, KG Andersen, I Shlyakhter, S Tabrizi, S Winnicki, A Yen et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1908638857179164245&btnI=1&hl=en">Identifying Recent Adaptations in Large-Scale Genomic Data</a>, Cell, 152 (4), 703-713</td></tr>
<tr><td width="100%">SB Montgomery, DL Goode, E Kvikstad, CA Albers, ZD Zhang, XJ Mu et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6865759942286846405&btnI=1&hl=en">The origin, evolution, and functional impact of short insertion–deletion variants identified in 179 human genomes</a>, Genome research, 23 (5), 749-761</td></tr>
<tr><td width="100%">P Awadalla, C Boileau, Y Payette, Y Idaghdour, JP Goulet, B Knoppers et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18198130870956227580&btnI=1&hl=en">Cohort profile of the CARTaGENE study: Quebec’s population-based biobank for public health and personalized genomics</a>, International journal of epidemiology, 42 (5), 1285-1299</td></tr>
<tr><td width="100%">ME Samuels, J Majewski, N Alirezaie, I Fernandez, F Casals, N Patey et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4627848150637343759&btnI=1&hl=en">Exome sequencing identifies mutations in the gene TTC7A in French-Canadian cases with hereditary multiple intestinal atresia</a>, Journal of medical genetics, 50 (5), 324-329</td></tr>
<tr><td width="100%">F Casals, A Hodgkinson, J Hussin, Y Idaghdour, V Bruat, T de Maillard et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4308911378155734887&btnI=1&hl=en">Whole-exome sequencing reveals a rapid change in the frequency of rare functional variants in a founding population of humans</a>, PLoS genetics, 9 (9), e1003815</td></tr>
<tr><td width="100%">J Hussin, D Sinnett, F Casals, Y Idaghdour, V Bruat, V Saillour, J Healy et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13887816649470281524&btnI=1&hl=en">Rare allelic forms of PRDM9 associated with childhood leukemogenesis</a>, Genome research, 23 (3), 419-430</td></tr>
<tr><td width="100%">A Abyzov, R Iskow, O Gokcumen, DW Radke, S Balasubramanian, B Pei et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=361325706864177889&btnI=1&hl=en">Analysis of variable retroduplications in human populations suggests coupling of retrotransposition to cell division</a>, Genome research, 23 (12), 2042-2052</td></tr>
<tr><td width="100%">MM Zilversmit, EK Chase, DS Chen, P Awadalla, KP Day, G McVean (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7308477108097725206&btnI=1&hl=en">Hypervariable antigen genes in malaria have ancient roots</a>, BMC Evolutionary Biology, 13 (1), 1-11</td></tr>
<tr><td width="100%">CL Yauk, JL Argueso, SS Auerbach, P Awadalla, SR Davis, DM DeMarini et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15883096888214518966&btnI=1&hl=en">Harnessing genomics to identify environmental determinants of heritable disease</a>, Mutation Research/Reviews in Mutation Research, 752 (1), 6-9</td></tr>
<tr><td width="100%">Y Idaghdour, P Awadalla (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7178244342445618623&btnI=1&hl=en">Exploiting Gene Expression Variation to Capture Gene-Environment Interactions for Disease</a>, Frontiers in Statistical Genetics and Methodology, 3, 228</td></tr>
<tr><td width="100%">A Hodgkinson, F Casals, Y Idaghdour, JC Grenier, RD Hernandez et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13393040247165785255&btnI=1&hl=en">Selective constraint, background selection, and mutation accumulation variability within and between human populations</a>, BMC genomics, 14 (1), 1-10</td></tr>
<tr><td width="100%">S Pattaradilokrat, J Mu, P Awadalla, X Su (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12336404474646951338&btnI=1&hl=en">Genome diversity and applications in genetic studies of the human malaria parasites Plasmodium falciparum and Plasmodium vivax</a>, Malaria parasites: comparative genomics, evolution and molecular biology, 59, 90</td></tr>
<tr><td width="100%">MP Hitz, LP Lemieux-Perreault, C Marshall, Y Feroz-Zada, R Davies et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2318057762678235929&btnI=1&hl=en">Correction: Rare Copy Number Variants Contribute to Congenital Left-Sided Heart Disease</a>, PLoS genetics, 9 (3)</td></tr>
<tr><td width="100%">M Capredon, C Preuss, J Grenier, V Bruat, T de Malliard, S Leclerc et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Impact of Rare Genetic Variations on Left Ventricular Outflow Tract Obstruction: Lessons From Whole Exome Sequencing</a>, Canadian Journal of Cardiology, 29 (10), S243</td></tr>
<tr><td width="100%">C Preuss, S Yang, M Capredon, M Samuels, P Awadalla, P Chetaille et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Composite Effects of Rare Variants in a Novel X-Linked Form of Congenital Heart Disease in the Québec Founder Population</a>, Canadian Journal of Cardiology, 29 (10), S87</td></tr>
<tr><td width="100%">C Preuss, M Capredon, G Asselin, M Dubé, M Samuels, P Awadalla et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Linkage Mapping and Whole-Exome Sequencing in a Family With Left Ventricular Outflow Tract Obstruction</a>, Canadian Journal of Cardiology, 29 (10), S88</td></tr>
<tr><td width="100%">R Hernandez, A Hodgkinson, F Casals, Y Idaghdour, JC Grenier et al. (2013) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Selective constraint, background selection, and mutation accumulation variability within and between human populations</a>, , </td></tr>
</tbody></table>
<h3>2012</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">1000 Genomes Project Consortium (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10753982274522830246,5455462239951988527,6769335483102770069&btnI=1&hl=en">An integrated map of genetic variation from 1,092 human genomes</a>, Nature, 491 (7422), 56-65</td></tr>
<tr><td width="100%">DG MacArthur, S Balasubrmanian, A Frankish, N Huang, J Morris et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8470955759670781782&btnI=1&hl=en">A systematic survey of loss-of-function variants in human protein-coding genes</a>, Science, 335 (6070), 823-828</td></tr>
<tr><td width="100%">Y Xue, Y Chen, Q Ayub, N Huang, EV Ball, M Mort, AD Phillips, K Shaw et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12836709416086617023&btnI=1&hl=en">Deleterious-and disease-allele prevalence in healthy individuals: insights from current predictions, mutation databases, and population-scale resequencing</a>, The American Journal of Human Genetics, 91 (6), 1022-1032</td></tr>
<tr><td width="100%">L Clarke, X Zheng-Bradley, R Smith, E Kulesha, C Xiao, I Toneva et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4468404008525756802&btnI=1&hl=en">The 1000 Genomes Project: data management and community access</a>, nature methods, 9 (5), 459-462</td></tr>
<tr><td width="100%">Y Idaghdour, J Quinlan, JP Goulet, J Berghout, E Gbeha, V Bruat et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18047116428005865991&btnI=1&hl=en">Evidence for additive and interaction effects of host genotype and infection in malaria</a>, Proceedings of the National Academy of Sciences, 109 (42), 16786-16793</td></tr>
<tr><td width="100%">F Casals, Y Idaghdour, J Hussin, P Awadalla (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8924836037215281250&btnI=1&hl=en">Next-generation sequencing approaches for genetic mapping of complex diseases</a>, Journal of neuroimmunology, 248 (1-2), 10-22</td></tr>
<tr><td width="100%">RA Cartwright, J Hussin, JEM Keebler, EA Stone, P Awadalla (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12403578722066447649&btnI=1&hl=en">A family-based probabilistic method for capturing de novo mutations from high-throughput short-read sequencing data</a>, Statistical applications in genetics and molecular biology, 11 (2)</td></tr>
<tr><td width="100%">R El Bikai, J Tremblay, P Dumas, O Šeda, L Šedová, P Awadalla et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">798 Hypertensive patients are more at risk of developing osteoporosis and having fractures due to their low bone mineral density</a>, Journal of Hypertension, 30, e231</td></tr>
<tr><td width="100%">M Piquer, L Alsina, M Alvaro, MA Martin-Mateos, F Casals, P Awadalla et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">CASE REPORT: INFLAMMATORY BOWEL DISEASE CROHN'S-LIKE, LIVER CIRRHOSIS, RECURRENT BLEPHARITIS AND NAIL HYPOPLASIA IN AN 6 YEAR OLD BOY</a>, JOURNAL OF CLINICAL IMMUNOLOGY, 32, 231-231</td></tr>
<tr><td width="100%">M Ivanga, J Sandoval, Y Idaghdour, G Corbeil, P Awadalla, O Seda et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">70 17q21. 31 CNV DOSE DEPENDENT EFFECT ON THE PREVALENCE OF HYPERTENSION AND DYSLIPIDEMIA COMORBIDITY</a>, Journal of Hypertension, 30, e22</td></tr>
<tr><td width="100%">R El Bikai, P Dumas, P Awadalla, J Temblay, C Laberge, LG Ste-Marie et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">P35 Évidence de risque accru d’ostéoporose dans le diabète et l’hypertension: importance de la masse musculaire.</a>, Diabetes & Metabolism, 38, A40</td></tr>
<tr><td width="100%">R El Bikai, P Dumas, P Awadalla, J Temblay, C Laberge, LG Ste-Marie et al. (2012) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Evidence of increased risk of osteoporosis in diabetes and hypertension: importance of muscle mass</a>, DIABETES & METABOLISM, 38, A40-A40</td></tr>
</tbody></table>
<h3>2011</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">P Danecek, A Auton, G Abecasis, CA Albers, E Banks, MA DePristo et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1468403490345182619&btnI=1&hl=en">The variant call format and VCFtools</a>, Bioinformatics, 27 (15), 2156-2158</td></tr>
<tr><td width="100%">RE Mills, K Walter, C Stewart, RE Handsaker, K Chen, C Alkan, A Abyzov et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3780005834850795417&btnI=1&hl=en">Mapping copy number variation by population-scale genome sequencing</a>, Nature, 470 (7332), 59-65</td></tr>
<tr><td width="100%">DF Conrad, JEM Keebler, MA DePristo, SJ Lindsay, Y Zhang, F Casals et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11519029210661809950&btnI=1&hl=en">Variation in genome-wide mutation rates within and between human families</a>, Nature Genetics, 43 (7), 712-714</td></tr>
<tr><td width="100%">S Gravel, BM Henn, RN Gutenkunst, AR Indap, GT Marth, AG Clark, F Yu et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11025770357227130872&btnI=1&hl=en">Demographic history and rare allele sharing among human populations</a>, Proceedings of the National Academy of Sciences, 108 (29), 11983-11988</td></tr>
<tr><td width="100%">RD Hernandez, JL Kelley, E Elyashiv, S Melton, A Auton, G McVean et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8309461225344424732&btnI=1&hl=en">Classic selective sweeps were rare in recent human evolution</a>, Science, 331 (6019), 920-924</td></tr>
<tr><td width="100%">C Stewart, D Kural, MP Str&ouml;mberg, JA Walker, MK Konkel, AM St&uuml;tz et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10780470007002407218&btnI=1&hl=en">A comprehensive map of mobile element insertion polymorphisms in humans</a>, PLoS genetics, 7 (8), e1002236</td></tr>
<tr><td width="100%">H Jiang, N Li, V Gopalan, MM Zilversmit, S Varma, V Nagarajan, J Li, J Mu et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8071996452370061112&btnI=1&hl=en">High recombination rates and hotspots in a Plasmodium falciparum genetic cross</a>, Genome biology, 12 (4), 1-15</td></tr>
<tr><td width="100%">RA Myers, F Casals, J Gauthier, FF Hamdan, J Keebler, AR Boyko et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14556653831271530377&btnI=1&hl=en">A population genetic approach to mapping neurological disorder genes using deep resequencing</a>, PLoS genetics, 7 (2), e1001318</td></tr>
<tr><td width="100%">OLH Branch, PL Sutton, C Barnes, JC Castro, J Hussin, P Awadalla et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4502312892411191618&btnI=1&hl=en">Plasmodium falciparum Genetic Diversity Maintained and Amplified Over 5 Years of a Low Transmission Endemic in the Peruvian Amazon</a>, Molecular biology and evolution, 28 (7), 1973-1986</td></tr>
<tr><td width="100%">J Hussin, MH Roy-Gagnon, R Gendron, G Andelfinger, P Awadalla (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=754173398365421909&btnI=1&hl=en">Age-dependent recombination rates in human pedigrees</a>, PLoS genetics, 7 (9), e1002251</td></tr>
<tr><td width="100%">F Casals, M Sikora, H Laayouni, L Montanucci, A Muntasell, R Lazarus et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18014968675599717670&btnI=1&hl=en">Genetic adaptation of the antibacterial human innate immunity network</a>, BMC evolutionary biology, 11 (1), 1-11</td></tr>
<tr><td width="100%">H Laayouni, L Montanucci, M Sikora, M Mele, GM Dall'Olio et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15111500937684463356&btnI=1&hl=en">Similarity in recombination rate estimates highly correlates with genetic differentiation in humans</a>, PLoS One, 6 (3), e17913</td></tr>
<tr><td width="100%">F Casals López, M Sikora, H Laayouni, L Montanucci et al. (2011) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Genetic adaptation of the antibacterial human innate immunity network</a>, BMC Evolutionary Biology., 2011; 11: 202</td></tr>
</tbody></table>
<h3>2010</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">GP Consortium (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2802397011957847088,11564418301439754252,9716915030219555947&btnI=1&hl=en">A map of human genome variation from population scale sequencing</a>, Nature, 467 (7319), 1061-1073</td></tr>
<tr><td width="100%">PH Sudmant, JO Kitzman, F Antonacci, C Alkan, M Malig, A Tsalenko et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12549860039147119343&btnI=1&hl=en">Diversity of human copy number variation and multicopy genes</a>, Science, 330 (6004), 641-646</td></tr>
<tr><td width="100%">W Yang, N Shen, DQ Ye, Q Liu, Y Zhang, XX Qian, N Hirankarn, D Ying et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=551281689962097333&btnI=1&hl=en">Genome-Wide Association Study in Asian Populations Identifies Variants in ETS1 and WDFY4 Associated with Systemic Lupus Erythematosus</a>, PLoS genetics, 6 (2), e1000841</td></tr>
<tr><td width="100%">J Gauthier, N Champagne, RG Lafrenière, L Xiong, D Spiegelman et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10348153153013635662&btnI=1&hl=en">De novo mutations in the gene encoding the synaptic scaffolding protein SHANK3 in patients ascertained for schizophrenia</a>, Proceedings of the National Academy of Sciences, 107 (17), 7863-7868</td></tr>
<tr><td width="100%">P Awadalla, J Gauthier, RA Myers, F Casals, FF Hamdan, AR Griffing et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14936703751096676552&btnI=1&hl=en">Direct measure of the de novo mutation rate in autism and schizophrenia cohorts</a>, The American Journal of Human Genetics, 87 (3), 316-324</td></tr>
<tr><td width="100%">DL Guernsey, H Jiang, J Hussin, M Arnold, K Bouyakdan, S Perry et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1119915313333009794&btnI=1&hl=en">Mutations in centrosomal protein CEP152 in primary microcephaly families linked to MCPH4</a>, The American Journal of Human Genetics, 87 (1), 40-51</td></tr>
<tr><td width="100%">J Mu, RA Myers, H Jiang, S Liu, S Ricklefs, M Waisberg, K Chotivanich et al. (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18364140065330697483&btnI=1&hl=en">Plasmodium falciparum genome-wide scans for positive selection, recombination hot spots and resistance to antimalarial drugs</a>, Nature genetics, 42 (3), 268-271</td></tr>
<tr><td width="100%">MM Zilversmit, SK Volkman, MA DePristo, DF Wirth, P Awadalla, DL Hartl (2010) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=813792412810960977&btnI=1&hl=en">Low-Complexity Regions in Plasmodium falciparum: Missing Links in the Evolution of an Extreme Genome</a>, Molecular biology and evolution, 27 (9), 2198-2209</td></tr>
</tbody></table>
<h3>2009</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">Psychiatric GWAS Consortium Coordinating Committee (2009) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18019779414881114896,10512421447170241018&btnI=1&hl=en">Genomewide association studies: history, rationale, and prospects for psychiatric disorders</a>, American Journal of Psychiatry, 166 (5), 540-556</td></tr>
</tbody></table>
<h3>2008</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">F Prugnolle, K McGee, J Keebler, P Awadalla (2008) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2034939749017193884&btnI=1&hl=en">Selection shapes malaria genomes and drives divergence between pathogens infecting hominids versus rodents</a>, BMC Evolutionary Biology, 8 (1), 1-9</td></tr>
</tbody></table>
<h3>2007</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">J Mu, P Awadalla, J Duan, KM McGee, J Keebler, K Seydel, GAT McVean et al. (2007) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=17159355322695150969&btnI=1&hl=en">Genome-wide variation and identification of vaccine targets in the Plasmodium falciparum genome</a>, Nature genetics, 39 (1), 126-130</td></tr>
<tr><td width="100%">J Bockhorst, F Lu, JH Janes, J Keebler, B Gamain, P Awadalla, X Su et al. (2007) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=16005909513906317848&btnI=1&hl=en">Structural polymorphism and diversifying selection on the pregnancy malaria vaccine candidate VAR2CSA</a>, Molecular and biochemical parasitology, 155 (2), 103-112</td></tr>
<tr><td width="100%">P Awadalla, XZ Su, K McGee (2007) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Recombination and Its Role in the Evolution of Pathogenic Microbes</a>, Encyclopedia of Infectious Diseases: Modern Methodologies, 163-173</td></tr>
</tbody></table>
<h3>2006</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">AR Trimnell, SM Kraemer, S Mukherjee, DJ Phippard, JH Janes et al. (2006) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9727806517718529216&btnI=1&hl=en">Global genetic diversity and evolution of var genes associated with placental and severe childhood malaria</a>, Molecular and biochemical parasitology, 148 (2), 169-180</td></tr>
<tr><td width="100%">MA Carbone, KW Jordan, RF Lyman, ST Harbison, J Leips, TJ Morgan et al. (2006) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4332485734456880645,7198248360083405931&btnI=1&hl=en">Phenotypic variation and natural selection at Catsup, a pleiotropic quantitative trait gene in Drosophila</a>, Current Biology, 16 (9), 912-919</td></tr>
<tr><td width="100%">M Jackson, AJ Watt, P Gautier, D Gilchrist, J Driehaus, GJ Graham et al. (2006) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12618012856114834109&btnI=1&hl=en">A murine specific expansion of the Rhox cluster involved in embryonic stem cell biology is under natural selection</a>, BMC genomics, 7 (1), 1-14</td></tr>
<tr><td width="100%">SM Kraemer, G Aggarwal, A Springer, S Nelson, A Trimnell, L Smith et al. (2006) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Unique patterns of recombination shape var gene structures and repertoires in P. falciparum</a>, The FASEB Journal, 20 (5), A909-A909</td></tr>
</tbody></table>
<h3>2005</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">J Mu, P Awadalla, J Duan, KM McGee, DA Joy, GAT McVean, X Su (2005) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18349333180403352476&btnI=1&hl=en">Recombination hotspots and population structure in Plasmodium falciparum</a>, PLOS Biology, 3 (10), e335</td></tr>
</tbody></table>
<h3>2004</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">DA Barbash, P Awadalla, AM Tarone, M Noor (2004) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3753726135135262872&btnI=1&hl=en">Functional Divergence Caused by Ancient Positive Selection of a Drosophila Hybrid Incompatibility Locus</a>, PLoS biology, 2 (6), e142</td></tr>
<tr><td width="100%">KK Shimizu, JM Cork, AL Caicedo, CA Mays, RC Moore, KM Olsen et al. (2004) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9425533439498989927&btnI=1&hl=en">Darwinian selection on a selfing locus</a>, Science, 306 (5704), 2081-2084</td></tr>
<tr><td width="100%">DT Haydon, ADS Bastos, P Awadalla (2004) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14728217129094901607&btnI=1&hl=en">Low linkage disequilibrium indicative of recombination in foot-and-mouth disease virus gene sequence alignments</a>, Journal of general virology, 85 (5), 1095-1100</td></tr>
</tbody></table>
<h3>2003</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">P Awadalla (2003) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15325626977767126206&btnI=1&hl=en">The evolutionary genomics of pathogen recombination</a>, Nature Reviews Genetics, 4 (1), 50-60</td></tr>
<tr><td width="100%">D Charlesworth, BK Mable, MH Schierup, C Bartolomé, P Awadalla (2003) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10163022268674451416&btnI=1&hl=en">Diversity and Linkage of Genes in the Self-Incompatibility Gene Family in Arabidopsis lyrata</a>, Genetics, 164 (4), 1519-1535</td></tr>
<tr><td width="100%">AA Abdel-Muhsin, MJ Mackinnon, P Awadalla, E Ali, S Suleiman et al. (2003) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9487902360119913334&btnI=1&hl=en">Local differentiation in Plasmodium falciparum drug resistance genes in Sudan</a>, Parasitology, 126 (5), 391-400</td></tr>
</tbody></table>
<h3>2002</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">G McVean, P Awadalla, P Fearnhead (2002) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14435325193172292612&btnI=1&hl=en">A coalescent-based method for detecting and estimating recombination from gene sequences</a>, Genetics, 160 (3), 1231-1241</td></tr>
<tr><td width="100%">MH Schierup, BK Mable, P Awadalla, D Charlesworth (2002) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10814214986340456496&btnI=1&hl=en">Identification and characterization of a polymorphic receptor kinase gene linked to the self-incompatibility locus of Arabidopsis lyrata (vol 158, pg 387, 2000)</a>, GENETICS, 160 (3), 1263-1263</td></tr>
</tbody></table>
<h3>2001</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">MH Schierup, BK Mable, P Awadalla, D Charlesworth (2001) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5453843408866671413&btnI=1&hl=en">Identification and Characterization of a Polymorphic Receptor Kinase Gene Linked to the Self-Incompatibility Locus of Arabidopsis lyrata</a>, Genetics, 158 (1), 387-399</td></tr>
<tr><td width="100%">A Eyre-Walker, P Awadalla (2001) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=7266020911985242016&btnI=1&hl=en">Does human mtDNA recombine?</a>, Journal of Molecular Evolution, 53 (4), 430-435</td></tr>
<tr><td width="100%">P Awadalla, D Walliker, H Babiker, M Mackinnon (2001) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11694777537369477101&btnI=1&hl=en">The question of Plasmodium falciparum population structure</a>, Trends in parasitology, 17 (8), 351-353</td></tr>
<tr><td width="100%">P Awadalla (2001) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Molecular Evolution of Self-incompatibility Loci in the Brassicacacea</a>, University of Edinburgh, </td></tr>
</tbody></table>
<h3>2000</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">D Charlesworth, P Awadalla, BK Mable, MH Schierup (2000) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=4904002299861707659&btnI=1&hl=en">Population-level studies of multiallelic self-incompatibility loci, with particular reference to Brassicaceae</a>, Annals of Botany, 85 (suppl_1), 227-239</td></tr>
<tr><td width="100%">P Awadalla (2000) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">The molecular evolution of self-incompatibility loci in the Brassicaceae family</a>, University of Edinburgh, </td></tr>
</tbody></table>
<h3>1999</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">P Awadalla, A Eyre-Walker, JM Smith (1999) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11422662261198195010&btnI=1&hl=en">Linkage disequilibrium and recombination in hominid mitochondrial DNA</a>, Science, 286 (5449), 2524-2525</td></tr>
<tr><td width="100%">P Awadalla, D Charlesworth (1999) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=17029669941802104800&btnI=1&hl=en">Recombination and selection at Brassica self-incompatibility loci</a>, Genetics, 152 (1), 413-425</td></tr>
</tbody></table>
<h3>1998</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">D Charlesworth, P Awadalla (1998) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9430888517876256705&btnI=1&hl=en">Flowering plant self-incompatibility: the molecular population genetics of Brassica S-loci</a>, Heredity, 81 (1), 1-9</td></tr>
</tbody></table>
<h3>1997</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">P Awadalla, K Ritland (1997) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5940656702483659158&btnI=1&hl=en">Microsatellite variation and evolution in the Mimulus guttatus species complex with contrasting mating systems.</a>, Molecular biology and evolution, 14 (10), 1023-1034</td></tr>
<tr><td width="100%">P Awadalla (1997) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6909766626090260001&btnI=1&hl=en">Microsatellite variation and evolution in mixed mating species of Mimulus (Scrophulariaceae).</a>, , </td></tr>
</tbody></table>
